



INCLUDEPATH += $${PWD}/../../

##### INTEGRATE POPULATION LIBRARY #########
POPULATIONPATH=.
!include($${PWD}/commonPopulation.pri)
!include($${PWD}/../../Common.pri)
HEADERS +=$${PWD}/../../dependency/ConvertorQImage.h
SOURCES +=$${PWD}/../../dependency/ConvertorQImage.cpp
############################################


INCLUDEPATH += . \
               $${PWD}/Operator/Algorithm/LinearAlgebra \
               $${PWD}/Operator/Algorithm/Representation \
               $${PWD}/Operator/Algorithm/Statistics \
               $${PWD}/Operator/Algorithm/Statistics \
               $${PWD}/Operator/Data/Plot \
               $${PWD}/Operator/Algorithm/Analysis/Physical \
               $${PWD}/Operator/Algorithm/PDE/Diffusion \
               $${PWD}/Operator/Algorithm/PDE/PhaseField \
               $${PWD}/Operator/Algorithm/Processing/Convolution \
               $${PWD}/Operator/Algorithm/Processing/Generator \
               $${PWD}/Operator/Algorithm/Processing/Neighborhood \
               $${PWD}/Operator/Algorithm/Processing/Point \
               $${PWD}/Operator/Algorithm/Processing/Recursive \
               $${PWD}/Operator/Algorithm/Processing/RegionGrowing \
               $${PWD}/Operator/Algorithm/Processing/Seed \
               $${PWD}/Operator/Algorithm/RandomGeometry/Art \
               $${PWD}/Operator/Algorithm/RandomGeometry/Color \
               $${PWD}/Operator/Algorithm/RandomGeometry/Geo \
               $${PWD}/Operator/Algorithm/RandomGeometry/Germ \
               $${PWD}/Operator/Algorithm/RandomGeometry/Grain \
               $${PWD}/Operator/Algorithm/RandomGeometry/Lattice \
               $${PWD}/Operator/Algorithm/RandomGeometry/Model \
               $${PWD}/Operator/Algorithm/Visualization/Label \
               $${PWD}/Operator/Algorithm/Visualization/OpenGl \
               $${PWD}/Operator/Data/Distribution/Arithmetic \
               $${PWD}/Operator/Data/Distribution/Convert \
               $${PWD}/Operator/Data/Distribution/InOut \
               $${PWD}/Operator/Data/Distribution/Tool \
               $${PWD}/Operator/Data/Distribution/Catalog/Continuous \
               $${PWD}/Operator/Data/Distribution/Catalog/Discrete \
               $${PWD}/Operator/Data/DMV/Arithmetic \
               $${PWD}/Operator/Data/DMV/Convert \
               $${PWD}/Operator/Data/DMV/InOut \
               $${PWD}/Operator/Data/DMV/catalog \
               $${PWD}/Operator/Data/DMV/Tool \
               $${PWD}/Operator/Data/ImageGrid/Affect \
               $${PWD}/Operator/Data/ImageGrid/Affect \
               $${PWD}/Operator/Data/ImageGrid/Arithmetic \
               $${PWD}/Operator/Data/ImageGrid/Format \
               $${PWD}/Operator/Data/ImageGrid/InOut \
               $${PWD}/Operator/Data/ImageGrid/Tool \
               $${PWD}/Operator/Data/Matrix/Arithmetic \
               $${PWD}/Operator/Data/Matrix/Convert \
               $${PWD}/Operator/Data/Matrix/InOut \
               $${PWD}/Operator/Data/Matrix/Tool \
               $${PWD}/Operator/Data/Point/Arithmetic \
               $${PWD}/Operator/Data/Point/InOut \
               $${PWD}/Operator/Data/Point/Tool \
               $${PWD}/Operator/Algorithm/Analysis/Geometry/Label \
               $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar \
               $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic \
               $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar \
               $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton \
               $${PWD}/../.. \
               $${PWD}/ \
               $${PWD}/Data \
               $${PWD}/Log \
               $${PWD}/Control
#!include($${PWD}/BindingCameleonInclude.pri)




HEADERS += \
    $${PWD}/Control/ControlMarkerImageGrid.h \
     $${PWD}/Control/ControlEditorPoint.h \
     $${PWD}/Control/ControlViewOpenGl.h \
     $${PWD}/Control/ControlViewImageGrid.h \
     $${PWD}/Control/ControlEditorMatrix.h \
     $${PWD}/Control/ControlViewMatrix.h \
    $${PWD}/Control/ControlEditorImageGrid.h \
    $${PWD}/Control/ControlViewDistribution.h \
    $${PWD}/Control/ControlViewImageGridValue.h \
    $${PWD}/Control/ControlViewPoint.h
SOURCES +=  \
     $${PWD}/Control/ControlEditorPoint.cpp \
     $${PWD}/Control/ControlViewOpenGl.cpp \
     $${PWD}/Control/ControlViewImageGrid.cpp \
     $${PWD}/Control/ControlEditorMatrix.cpp \
     $${PWD}/Control/ControlViewMatrix.cpp \
    $${PWD}/Control/ControlEditorImageGrid.cpp \
    $${PWD}/Control/ControlViewDistribution.cpp \
    $${PWD}/Control/ControlViewImageGridValue.cpp \
    $${PWD}/Control/ControlViewPoint.cpp \
    $${PWD}/Control/ControlMarkerImageGrid.cpp
SOURCES +=  \
     $${PWD}/Data/DataOpenGl.cpp \
     $${PWD}/Data/DataImageGrid.cpp \
     $${PWD}/Data/DataDistribution.cpp \
     $${PWD}/Data/DataDistributionMultiVariate.cpp \
     $${PWD}/Data/DataPoint.cpp \
     $${PWD}/Data/DataMatrix.cpp \
     $${PWD}/Data/DataGraph.cpp \
     $${PWD}/Data/DataPlot.cpp \
    $${PWD}/Log/PopulationLog.cpp \
     $${PWD}/Data/DataGrainList.cpp \
     $${PWD}/PopulationDictionnary.cpp
HEADERS += \
     $${PWD}/Data/DataImageGrid.h \
     $${PWD}/Data/DataDistribution.h \
     $${PWD}/Data/DataDistributionMultiVariate.h \
     $${PWD}/Data/DataPoint.h \
     $${PWD}/Data/DataMatrix.h \
     $${PWD}/Data/DataGraph.h \
     $${PWD}/Data/DataGrainList.h \
     $${PWD}/Data/DataOpenGl.h \
     $${PWD}/PopulationDictionnary.h \
     $${PWD}/Data/DataPlot.h \
     $${PWD}/Log/PopulationLog.h



HEADERS += $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorDeterminantMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorEigenValueMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorEigenVectorMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorGenerate2DRotationMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorGenerate3DRotationMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorIdentityMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorInverseMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorOrthogonalMatrix.h \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorTraceMatrix.h \
           $${PWD}/Operator/Algorithm/Representation/OperatorFFTImageGrid.h \
           $${PWD}/Operator/Algorithm/Representation/OperatorFFTInverseImageGrid.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorArgMinDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorComputedStaticticsDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertCumulativeDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertProbabilityDistributionDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertStepFunctionDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorDerivateDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorDistanceDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorInnerProductDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorIntegralDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMaxValueDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMinValueDistribution.h \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMomentDistribution.h \
           $${PWD}/Operator/Data/Plot/OperatorAddGraphPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorBlankPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorFromDistributionPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorFromMatrixPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorFromTablePlot.h \
           $${PWD}/Operator/Data/Plot/OperatorPopPointPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorPushPointPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetAlphaPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetBrushColorPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetColorPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetLegendPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetLogXAxisPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetLogYAxisPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetTitlePlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetWidthPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetXAxisLegendPlot.h \
           $${PWD}/Operator/Data/Plot/OperatorSetYAxisLegendPlot.h \
           $${PWD}/Operator/Algorithm/Analysis/Physical/OperatorDiffusionCoefficientImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Physical/OperatorPermeabilityImageGrid.h \
           $${PWD}/Operator/Algorithm/PDE/Diffusion/OperatorNonLinearAnistropicDiffusionImageGrid.h \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorAllenCahnImageGrid.h \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorCurvatureFromPhaseFieldImageGrid.h \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorGetFieldFromMultiPhaseFieldImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorConvolutionImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorSobelImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Generator/OperatorConstImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Generator/OperatorRandomFieldImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorAlternateSequentialCOImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/AlternateSequentialCOStructural.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorAlternateSequentialOCImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/AlternateSequentialOCStructural.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorClosingImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorClosingStructuralImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorDilationImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorDilationStructuralImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorErosionImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorErosionStructuralImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorHitOrMissImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorMeanImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorMedianImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorOpeningImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorOpeningStructuralImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorContrastScaleImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorfofxImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorHeteregeneousRandomFieldImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorHistogramShiftMeanImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorLabelOrganizeImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorScaleDynamicGreyLevelImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorThresholdImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorGradientDericheImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorRecursiveOrder1ImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorRecursiveOrder2ImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorSmoothDericheImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorAdamsBischofImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorCluster2LabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorClusterMaxImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDilationFastBinaryImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDistanceImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDynamicImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorErosionFastBinaryImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorGeodesicReconstructionImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorHoleFillingImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorMinimaImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorVoronoiTesselationImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorWatershedImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorBinaryFromLabelSelectionImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorBinaryFromSingleSeedInLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorLabelAddImageGrid.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Art/OperatorRandomWalkGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorColorFromImageGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorRandomBlackOrWhiteGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorRandomColorGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorGaussianRandomFieldImageGrid.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorAnnealingSimulatedImageGrid.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorRandomStructureImageGrid.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorHardCoreFilterGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorMinOverlapGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorRandomNonUniformPointGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorRandomUniformPointGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorBoxGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorCylinderGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorEllipsoidGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorGrainFromImageGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorPolyhedraGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorRhombohedronGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorSphereGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Lattice/OperatorContinuousToLatticeGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorBooleanGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorDeadLeaveGrainList.h \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorTransparencyGrainList.h \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorAverageImageGrid.h \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorForegroundImageGrid.h \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorGradationFromLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorRandomFromLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorAdditionOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorCubeOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorGetPlaneOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorGraphOpenGl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorLatticeSurfaceOpenGl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorLineOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorMarchingCubeBinaryImageGridOpenGl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorMarchingCubeColorImageGridOpenGl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorSetAmbientOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorSetColorOpengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/operatorsetdiffuseopengl.h \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorTransparencyOpengl.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorAddDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorCompoDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorDivDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorInverseDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorMaxDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorMultDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorOppositeDistribution.h \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorSubDistribution.h \
           $${PWD}/Operator/Data/Distribution/Convert/OperatorToMatrixDistribution.h \
           $${PWD}/Operator/Data/Distribution/InOut/OperatorLoadDistribution.h \
           $${PWD}/Operator/Data/Distribution/InOut/OperatorSaveDistribution.h \
           $${PWD}/Operator/Data/Distribution/Tool/OperatorfofXDistribution.h \
           $${PWD}/Operator/Data/Distribution/Tool/OperatorRandomVariableDistribution.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorAddDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorCompoDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorDivDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorInverseDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorMaxDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorMultDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorOppositeDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorSubDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/InOut/OperatorLoadDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/InOut/OperatorSaveDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Tool/OperatorfofXDistributionMultiVariate.h \
           $${PWD}/Operator/Data/DMV/Tool/OperatorRandomVariableDistributionMultiVariate.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorGetPlaneImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorGetPointImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetBallImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetPlaneImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetPointImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorWhiteFaceImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorAddImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorAddScalarImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDiffImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDivImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDivScalarImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMaxImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMinImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMinuxImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMultImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMultScalarImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorSubImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorSubScalarImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert1ByteImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert2ByteImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert4ByteImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertColor2GreyImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertColor2RGBImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertComplex2ScalarImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertFloatImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertGrey2ColorImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImage3DToVec.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImageGrid2ImageQT.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImageQT2ImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertRGB2ColorImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertScalar2ComplexImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertVectorToImage3D.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorIsReadableImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadFromDirectoryImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadRawImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveFromDirectoryImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveRawImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorBlankImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorCropImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorGetSizeImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorInformationImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorInsertImageImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorIsEmptyImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorLabelToImageGridVectorImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorResizeImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorRotationImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorScaleImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorTranslationImageGrid.h \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorTypeImageGrid.h \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorAddMatrix.h \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultMatrix.h \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultMatrixScalar.h \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultVectorMatrix.h \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorSubMatrix.h \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorConvertFromTableMatrix.h \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorConvertToTableMatrix.h \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorFromImageGridMatrix.h \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorToImageGridMatrix.h \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorBlankMatrix.h \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorLoadMatrix.h \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorSaveMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetColMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetRawMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorResizeMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetColMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetRawMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSizeMatrix.h \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorTransposeMatrix.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorAddScalarVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorAddVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMaxVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMinVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultEachTermVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultVec.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultVectorScalar.h \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorSubVec.h \
           $${PWD}/Operator/Data/Point/InOut/OperatorBlank2DVec.h \
           $${PWD}/Operator/Data/Point/InOut/operatorblank3dVec.h \
           $${PWD}/Operator/Data/Point/InOut/OperatorBlankVec.h \
           $${PWD}/Operator/Data/Point/InOut/OperatorLoadPoint.h \
           $${PWD}/Operator/Data/Point/InOut/OperatorSavePoint.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorGetPoint.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorMultCoordinateVec.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorPushBackValueVec.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorResizePoint.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorSetPoint.h \
           $${PWD}/Operator/Data/Point/Tool/OperatorSizePoint.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionAreaLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionContactLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionFeretDiameterLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionPerimeterLabelImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorAreaImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorHistogramImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorMaxValueImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorMinValueImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorPerimeterImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorVERPointHistogramImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorVERPointPorosityImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorChordImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationDirectionByFFTImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationGreyLevelImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorFractalBoxImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorLDistanceImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorMatheronGranulometryImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorEulerPoincareImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorGeometricalTortuosityImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationErosionImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationOpeningImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorLinkVertexWithEdgeImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorMedialAxisImageGrid.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorThinningAtConstantTopology.h \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorVertexAndEdgeFromSkeletonImageGrid.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorBoxDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorDiracDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorExponentielDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorFromMatrixDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorNormalDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorRegularExpressionDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorUniformRealDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorBinomialDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorPencilDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorPoissonDistribution.h \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorUniformIntDistribution.h \
          $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorSmoothGaussianImageGrid.h  \
          $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorGradientMagnitudeGaussianImageGrid.h \
    $${PWD}/Operator/Data/DMV/catalog/OperatorCoupledDistributionMultiVariate.h \
    $${PWD}/Operator/Data/DMV/catalog/OperatorIndependantDistributionMultiVariate.h \
    $${PWD}/Operator/Data/DMV/catalog/OperatorExpressionDistributionMultiVariate.h \
    $${PWD}/Operator/Data/DMV/catalog/OperatorNormalDistributionMultiVariate.h \
    $${PWD}/Operator/Algorithm/Statistics/OperatorArgMaxDistributionMultiVariate.h \
    $${PWD}/Operator/Algorithm/Statistics/OperatorArgMaxDistribution.h \
    $${PWD}/Operator/Data/DMV/catalog/OperatorFromDistributionDistributionMultiVariate.h \
    $${PWD}/Operator/Algorithm/Statistics/OperatorConvertProbabilityDistributionMultiVariateDistributionMultiVariate.h \
     $${PWD}/Operator/Algorithm/Statistics/OperatorArgMinDistributionMultiVariate.h \
     $${PWD}/Operator/Algorithm/Statistics/OperatorMomentDistributionMultiVariate.h \
     $${PWD}/Operator/Algorithm/Statistics/OperatorMaxValueDistributionMultiVariate.h \
    $${PWD}/Operator/Algorithm/Statistics/OperatorMinValueDistributionMultiVariate.h \
    $${PWD}/Operator/Algorithm/Statistics/OperatorIntegralDistributionMultiVariate.h \
    $${PWD}/Operator/Data/ImageGrid/InOut/OperatorTryLoad.h

SOURCES += $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorDeterminantMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorEigenValueMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorEigenVectorMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorGenerate2DRotationMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorGenerate3DRotationMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorIdentityMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorInverseMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorOrthogonalMatrix.cpp \
           $${PWD}/Operator/Algorithm/LinearAlgebra/OperatorTraceMatrix.cpp \
           $${PWD}/Operator/Algorithm/Representation/OperatorFFTImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Representation/OperatorFFTInverseImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorArgMinDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorComputedStaticticsDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertCumulativeDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertProbabilityDistributionDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorConvertStepFunctionDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorDerivateDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorDistanceDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorInnerProductDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorIntegralDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMaxValueDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMinValueDistribution.cpp \
           $${PWD}/Operator/Algorithm/Statistics/OperatorMomentDistribution.cpp \
           $${PWD}/Operator/Data/Plot/OperatorAddGraphPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorBlankPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorFromDistributionPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorFromMatrixPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorFromTablePlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorPopPointPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorPushPointPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetAlphaPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetBrushColorPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetColorPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetLegendPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetLogXAxisPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetLogYAxisPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetTitlePlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetWidthPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetXAxisLegendPlot.cpp \
           $${PWD}/Operator/Data/Plot/OperatorSetYAxisLegendPlot.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Physical/OperatorDiffusionCoefficientImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Physical/OperatorPermeabilityImageGrid.cpp \
           $${PWD}/Operator/Algorithm/PDE/Diffusion/OperatorNonLinearAnistropicDiffusionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorAllenCahnImageGrid.cpp \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorCurvatureFromPhaseFieldImageGrid.cpp \
           $${PWD}/Operator/Algorithm/PDE/PhaseField/OperatorGetFieldFromMultiPhaseFieldImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorConvolutionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorSobelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Generator/OperatorConstImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Generator/OperatorRandomFieldImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorAlternateSequentialCOImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/AlternateSequentialCOStructural.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorAlternateSequentialOCImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/AlternateSequentialOCStructural.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorClosingImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorClosingStructuralImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorDilationImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorDilationStructuralImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorErosionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorErosionStructuralImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorHitOrMissImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorMeanImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorMedianImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorOpeningImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Neighborhood/OperatorOpeningStructuralImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorContrastScaleImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorfofxImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorHeteregeneousRandomFieldImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorHistogramShiftMeanImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorLabelOrganizeImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorScaleDynamicGreyLevelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Point/OperatorThresholdImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorGradientDericheImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorRecursiveOrder1ImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorRecursiveOrder2ImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Recursive/OperatorSmoothDericheImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorAdamsBischofImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorCluster2LabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorClusterMaxImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDilationFastBinaryImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDistanceImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorDynamicImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorErosionFastBinaryImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorGeodesicReconstructionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorHoleFillingImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorMinimaImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorVoronoiTesselationImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/RegionGrowing/OperatorWatershedImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorBinaryFromLabelSelectionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorBinaryFromSingleSeedInLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Processing/Seed/OperatorLabelAddImageGrid.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Art/OperatorRandomWalkGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorColorFromImageGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorRandomBlackOrWhiteGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Color/OperatorRandomColorGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorGaussianRandomFieldImageGrid.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorAnnealingSimulatedImageGrid.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Geo/OperatorRandomStructureImageGrid.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorHardCoreFilterGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorMinOverlapGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorRandomNonUniformPointGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Germ/OperatorRandomUniformPointGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorBoxGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorCylinderGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorEllipsoidGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorGrainFromImageGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorPolyhedraGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorRhombohedronGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Grain/OperatorSphereGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Lattice/OperatorContinuousToLatticeGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorBooleanGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorDeadLeaveGrainList.cpp \
           $${PWD}/Operator/Algorithm/RandomGeometry/Model/OperatorTransparencyGrainList.cpp \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorAverageImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorForegroundImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorGradationFromLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Visualization/Label/OperatorColorRandomFromLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorAdditionOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorCubeOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorGetPlaneOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorGraphOpenGl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorLatticeSurfaceOpenGl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorLineOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorMarchingCubeBinaryImageGridOpenGl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorMarchingCubeColorImageGridOpenGl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorSetAmbientOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorSetColorOpengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/operatorsetdiffuseopengl.cpp \
           $${PWD}/Operator/Algorithm/Visualization/OpenGl/OperatorTransparencyOpengl.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorAddDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorCompoDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorDivDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorInverseDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorMaxDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorMultDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorOppositeDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Arithmetic/OperatorSubDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Convert/OperatorToMatrixDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/InOut/OperatorLoadDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/InOut/OperatorSaveDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Tool/OperatorfofXDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Tool/OperatorRandomVariableDistribution.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorAddDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorCompoDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorDivDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorInverseDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorMaxDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorMultDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorOppositeDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Arithmetic/OperatorSubDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/InOut/OperatorLoadDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/InOut/OperatorSaveDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Tool/OperatorfofXDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/DMV/Tool/OperatorRandomVariableDistributionMultiVariate.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorGetPlaneImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorGetPointImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetBallImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetPlaneImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorSetPointImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Affect/OperatorWhiteFaceImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorAddImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorAddScalarImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDiffImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDivImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorDivScalarImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMaxImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMinImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMinuxImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMultImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorMultScalarImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorSubImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Arithmetic/OperatorSubScalarImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert1ByteImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert2ByteImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvert4ByteImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertColor2GreyImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertColor2RGBImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertComplex2ScalarImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertFloatImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertGrey2ColorImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImage3DToVector.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImageGrid2ImageQT.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertImageQT2ImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertRGB2ColorImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertScalar2ComplexImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Format/OperatorConvertVectorToImage3D.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorIsReadableImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadFromDirectoryImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorLoadRawImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveFromDirectoryImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/InOut/OperatorSaveRawImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorBlankImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorCropImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorGetSizeImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorInformationImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorInsertImageImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorIsEmptyImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorLabelToImageGridVectorImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorResizeImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorRotationImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorScaleImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorTranslationImageGrid.cpp \
           $${PWD}/Operator/Data/ImageGrid/Tool/OperatorTypeImageGrid.cpp \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorAddMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultMatrixScalar.cpp \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorMultVectorMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Arithmetic/OperatorSubMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorConvertFromTableMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorConvertToTableMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorFromImageGridMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Convert/OperatorToImageGridMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorBlankMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorLoadMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/InOut/OperatorSaveMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetColMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorGetRawMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorResizeMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetColMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSetRawMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorSizeMatrix.cpp \
           $${PWD}/Operator/Data/Matrix/Tool/OperatorTransposeMatrix.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorAddScalarVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorAddVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMaxVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMinVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultEachTermVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultVector.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorMultVectorScalar.cpp \
           $${PWD}/Operator/Data/Point/Arithmetic/OperatorSubVector.cpp \
           $${PWD}/Operator/Data/Point/InOut/OperatorBlank2DVector.cpp \
           $${PWD}/Operator/Data/Point/InOut/operatorblank3dvector.cpp \
           $${PWD}/Operator/Data/Point/InOut/OperatorBlankVector.cpp \
           $${PWD}/Operator/Data/Point/InOut/OperatorLoadPoint.cpp \
           $${PWD}/Operator/Data/Point/InOut/OperatorSavePoint.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorGetPoint.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorMultCoordinateVector.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorPushBackValueVector.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorResizePoint.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorSetPoint.cpp \
           $${PWD}/Operator/Data/Point/Tool/OperatorSizePoint.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionAreaLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionContactLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionFeretDiameterLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Label/OperatorRepartitionPerimeterLabelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorAreaImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorHistogramImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorMaxValueImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorMinValueImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorPerimeterImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorVERPointHistogramImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Scalar/OperatorVERPointPorosityImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorChordImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationDirectionByFFTImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationGreyLevelImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorCorrelationImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorFractalBoxImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorLDistanceImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Geometry/Statistic/OperatorMatheronGranulometryImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorEulerPoincareImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorGeometricalTortuosityImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationErosionImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Scalar/OperatorPercolationOpeningImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorLinkVertexWithEdgeImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorMedialAxisImageGrid.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorThinningAtConstantTopology.cpp \
           $${PWD}/Operator/Algorithm/Analysis/Topology/Skeleton/OperatorVertexAndEdgeFromSkeletonImageGrid.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorBoxDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorDiracDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorExponentielDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorFromMatrixDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorNormalDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorRegularExpressionDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Continuous/OperatorUniformRealDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorBinomialDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorPencilDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorPoissonDistribution.cpp \
           $${PWD}/Operator/Data/Distribution/Catalog/Discrete/OperatorUniformIntDistribution.cpp \
          $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorSmoothGaussianImageGrid.cpp \
          $${PWD}/Operator/Algorithm/Processing/Convolution/OperatorGradientMagnitudeGaussianImageGrid.cpp \
    $${PWD}/Operator/Data/DMV/catalog/OperatorCoupledDistributionMultiVariate.cpp \
    $${PWD}/Operator/Data/DMV/catalog/OperatorIndependantDistributionMultiVariate.cpp \
    $${PWD}/Operator/Data/DMV/catalog/OperatorExpressionDistributionMultiVariate.cpp \
    $${PWD}/Operator/Data/DMV/catalog/OperatorNormalDistributionMultiVariate.cpp \
    $${PWD}//Operator/Algorithm/Statistics/OperatorArgMaxDistributionMultiVariate.cpp \
    $${PWD}//Operator/Algorithm/Statistics/OperatorArgMaxDistribution.cpp \
    $${PWD}//Operator/Data/DMV/catalog/OperatorFromDistributionDistributionMultiVariate.cpp \
   $${PWD}//Operator/Algorithm/Statistics/OperatorConvertProbabilityDistributionMultiVariateDistributionMultiVariate.cpp \
    $${PWD}//Operator/Algorithm/Statistics/OperatorArgMinDistributionMultiVariate.cpp \
   $${PWD}//Operator/Algorithm/Statistics/OperatorMomentDistributionMultiVariate.cpp \
    $${PWD}//Operator/Algorithm/Statistics/OperatorMaxValueDistributionMultiVariate.cpp \
   $${PWD}//Operator/Algorithm/Statistics/OperatorMinValueDistributionMultiVariate.cpp \
    $${PWD}/Operator/Algorithm/Statistics/OperatorIntegralDistributionMultiVariate.cpp\
    $${PWD}/Operator/Data/ImageGrid/InOut/OperatorTryLoad.cpp
