if(NOT WITH_X11)
    message(STATUS "Not X11 library")
    return()
endif()
if(UNIX)
    find_package(X11 REQUIRED)
    if(NOT X11_FOUND)
        message(FATAL_ERROR "Failed to find X11 which is required")
    else(NOT X11_FOUND)
        set(POPULATION_LIBRARY ${POPULATION_LIBRARY} ${X11_LIBRARIES})
        set(HAVE_X11 YES)
        message(STATUS "Find X11")
    endif(NOT X11_FOUND)
endif(UNIX)
