if(NOT WITH_OPENMP)
    message(STATUS "Not paralization with OPENMP")
    return()
endif()
find_package(OpenMP)
if(OPENMP_FOUND)
    message(STATUS "found OPENMP")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    set(HAVE_OPENMP YES)
else()
     message(STATUS "No OPENMP finded")
endif()

