if(NOT WITH_X11)
    message(STATUS "X11 Not")
    return()
endif()
if(UNIX)
    find_package(X11 REQUIRED)
    if(NOT X11_FOUND)
        message(FATAL_ERROR "X11 NOT FOUND")
    else(NOT X11_FOUND)
        set(POPULATION_LIBRARY ${POPULATION_LIBRARY} ${X11_LIBRARIES})
        set(HAVE_X11 YES)
        message(STATUS "X11 FOUND")
    endif(NOT X11_FOUND)
endif(UNIX)
