if(NOT WITH_THREAD)
	  message(STATUS "Not thread library")
  	return()
endif()
if(UNIX)
  	find_package (Threads REQUIRED)
		if(CMAKE_USE_PTHREADS_INIT)		
                set(POPULATION_LIBRARY ${POPULATION_LIBRARY} ${CMAKE_THREAD_LIBS_INIT} )
    		set(HAVE_THREAD YES)
		endif(CMAKE_USE_PTHREADS_INIT)
endif(UNIX)

if(WIN32)
    set(HAVE_THREAD YES)
endif(WIN32)
