if(NOT WITH_CUDA)
   message(STATUS "CUDA NOT")
   return()
endif()

find_package(CUDA)
if(CUDA_VERSION)
   message(STATUS "CUDA FOUND version ${CUDA_VERSION}")
   set(HAVE_CUDA true)
else()
   message(STATUS "CUDA NOT FOUND")
   set(HAVE_CUDA false)
endif(CUDA_VERSION)
