if(NOT WITH_OPENMP)
    message(STATUS "Not paralization with OPENMP")
    return()
endif()
find_package(OpenMP)
if(OPENMP_FOUND)
    message(STATUS "OPENMP FOUND")
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_C_FLAGS}")
    #set(POPULATION_LIBRARY ${POPULATION_LIBRARY} ${OpenMP_C_FLAGS})
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    set(HAVE_OPENMP YES)
else()
     message(STATUS "OPENMP NOT FOUND")
endif()

